### Verbo GET – listar todos os clientes
GET http://localhost:8000/cliente/ HTTP/1.1


### Verbo GET – listar um cliente pelo ID
GET http://localhost:8000/cliente/10 HTTP/1.1


### Verbo POST – adicionar cliente
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome": "João da Silva",
    "cpf": "12345678900",
    "telefone": "49999999999"
}


### Verbo PUT – atualizar cliente
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
content-type: application/json

{
    "nome": "Alisson Rafael da cruz velho",
    "cpf": "12345678900",
    "telefone": "49988888888"
}


### Verbo DELETE – excluir cliente
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1