#Alisson Rafael da Cruz Velho
#http://localhost:8000/docs#/ Link de acesso da página principal.
### Verbo GET – listar todos os produtos
GET http://localhost:8443/produto/ HTTP/1.1


### Verbo GET – listar um produto pelo ID
GET http://localhost:8000/produto/1 HTTP/1.1


### Verbo POST –eaea adicionar produto
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome": "pastel de carne e ovo",
    "descricao": "vai carne e ovo",
    "foto": "MTIzNA==",
    "valor_unitario": 10
}

### Verbo PUT – atualizar produto
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome": "bolinho de  carne",
    "descricao": "com carne moída",
    "foto": "MTIzNA==",
    "valor_unitario": 4200
}

### Verbo DELETE – excluir produto
DELETE http://127.0.0.1:8000/produto/2 HTTP/1.1
